export enum TECHNOLOGY {
  REACT = 'react',
  NEXTJS = 'nextjs',
  GATSBY = 'gatsby',
  NESTJS = 'nestjs',
  EXPRESS = 'express',
  EXPO = 'expo',
  REACT_NATIVE = 'reactnative',
  NPM = 'npm',
  ARDUINO = 'arduino',
  ASPDOTNET = 'aspnet',
  WPF = 'wpf',
  XAMARIN = 'xamarin',
  SPRING = 'spring',
  UNITY = 'unity',

  VITE = 'vite',
  GIT = 'git',
  DOCKER = 'docker',
  PM2 = 'pm2',
  NGINX = 'nginx',

  STRAPI = 'strapi',
  WORDPRESS = 'wordpress',

  POSTGRESQL = 'postgresql',
  MSSQL = 'mssql',
  ORACLE = 'oracle',
  MYSQL = 'mysql',
  SQLITE = 'sqlite',
  MONGODB = 'mongodb',
  REDIS = 'redis',
  ELASTICSEARCH = 'elasticsearch',

  JAVA_SCRIPT = 'js',
  TYPE_SCRIPT = 'ts',
  HTML = 'html',
  CSS = 'css',
  SCSS = 'scss',
  SQL = 'sql',
  CS = 'cs',
  CPP = 'cpp',
  JAVA = 'java',
  BASH = 'bash',

  AZURE = 'azure',
  VERCEL = 'vercel',
  GITHUB = 'github',
  GITLAB = 'gitlab',
  BITBUCKET = 'bitbucket',
  JIRA = 'jira',
  TRELLO = 'trello',
  SENTRY = 'sentry',
  RESEND = 'resend',
  STRIPE = 'stripe',
  TWILIO = 'twilio',

  PRISMA = 'prisma',
  DRIZZLE = 'drizzle',
  TYPEORM = 'typeorm',
  SEQUELIZE = 'sequelize',
  GRAPHQL = 'graphql',
  REACT_QUERY = 'reactquery',
  ZUSTAND = 'zustand',
  JEST = 'jest',
  ZOD = 'zod',
  JWT = 'jwt',
  OAUTH = 'oauth',
  RABBITMQ = 'rabbitmq',
  FRAMER_MOTION = 'framermotion',
  CHARTJS = 'chartjs',
  THREEJS = 'threejs',
  LOTTIE_FILES = 'lottiefiles',
  TAILWIND = 'tailwind',

  VSCODE = 'vscode',
  POSTMAN = 'postman',
  LIGHTHOUSE = 'lighthouse',
  DATAGRIP = 'datagrip',
  VIM = 'vim',
  VISUAL_STUDIO = 'visualstudio',
  INTELLIJ = 'intellij',
  BLENDER = 'blender',
}
