// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Metadata": {
    "title": "Bartosz Art",
    "description": "Bartosz Art — Full-Stack Developer and Software Engineer focused on building modern, high-performance, user-centered applications and systems."
  },
  "Nav": {
    "about": "About",
    "projects": "Projects",
    "offer": "Services",
    "contact": "Contact"
  },
  "HomePage": {
    "roles": [
      "Full-Stack Developer",
      "Software Engineer",
      "Maritime Yacht Skipper"
    ]
  },
  "ProjectsPage": {
    "title": "Projects",
    "scope": "Scope",
    "techstack": "Tech Stack",
    "liveDemo": "Live Demo",
    "repository": "Source Code",

    "web": "Website",
    "mobile": "Mobile Application",
    "cms": "Content Management System",
    "server": "Server",
    "db": "Database"
  },

  "Projects": {
    "bujnickaDent": {
      "snippet": "Comprehensive dental practice management system with a strong focus on security and data protection. It enables online appointment booking, schedule management, notifications, and administrative workflows. The solution has been deployed and supports the clinic's daily operations."
    },
    "modernCar": {
      "snippet": "Commercial website for an automotive detailing studio specializing in vehicle care, protection, and customization. Built using plain HTML, CSS, and JavaScript, with a strong emphasis on effective service presentation, smooth animations, and full responsiveness across mobile and desktop devices."
    },
    "kam": {
      "snippet": "Modern website for an accounting firm featuring a content management system that enables independent content editing. Designed to build trust, strengthen the company's professional image, showcase services in a clear and accessible way, and support effective client acquisition."
    }
  },

  "Forms": {
    "contactDetails": "Contact Details",
    "ideaTitle": "Have an interesting idea?",
    "ideaDescription": "Describe it below or simply ask a question.",
    "message": "Describe your idea, project, or question",
    "submit": "Send Form",
    "removeFile": "Remove file",

    "fullName": "Full Name",
    "email": "Email",
    "phone": "Phone Number (optional)",
    "attachments": "Add attachments",
    "dataProcessingConsent": "I consent to the processing of my personal data"
  },

  "FormStatuses": {
    "loadingToast": "Training carrier pigeon...",
    "successToast": "The pigeon made it! I'll get back to you soon.",
    "validationErrorToast": "The pigeon refused takeoff due to invalid cargo.",
    "generalErrorToast": "The pigeon went on strike. Please try again."
  },

  "ValidationErrors": {
    "fullName": {
      "required": "Please enter your full name.",
      "min": "Full name must be at least {count, plural, one {# character} other {# characters}} long.",
      "max": "Full name cannot exceed {count, plural, one {# character} other {# characters}}."
    },
    "email": {
      "invalid": "Please enter a valid email address.",
      "max": "Email address cannot exceed {count, plural, one {# character} other {# characters}}."
    },
    "phone": {
      "invalid": "Please enter a valid phone number."
    },
    "message": {
      "min": "Please provide more details about your project or inquiry.",
      "max": "Message address cannot exceed {count, plural, one {# character} other {# characters}}."
    },
    "dataProcessingConsent": {
      "required": "Please accept the data processing consent to continue."
    },
    "attachments": {
      "maxCount": "You can upload up to {count, plural, one {# file} other {# files}}.",
      "maxSize": "Each file must be smaller than {count, number} MB.",
      "invalidType": "Unsupported file format. Please upload images, PDF, Office documents, text files, or archives."
    }
  }
};
export default messages;